Selenium_HW
Den1sProkrastinator/TAF pull request #1
Opened 2022-04-23 19:42 UTC by Den1sProkrastinator

2022-04-25 11:27 UTC, wildpioneer requested changes
Внесены комментарии

2022-04-25 11:27 UTC, wildpioneer commented on src/test/java/tests/SmokeTestCalculatorsLaminat.java
> +        calculateButton.click();
Отсутствует шаг выбора Способа укладки ламината из dropdown

2022-04-25 11:27 UTC, wildpioneer commented on src/test/java/tests/SmokeTestCalculatorsLaminat.java
> +
Форматирование документа - исправить

2022-04-25 11:34 UTC, Den1sProkrastinator commented on src/test/java/tests/SmokeTestCalculatorsLaminat.java
> +        calculateButton.click();
‘Способ укладки ламината’ из выпадающего списка' - не было указано какой способ выбрать вот я и оставил дефолтный вариант )

2022-04-25 12:28 UTC, DenisKharitanuk commented on src/test/java/tests/SmokeTestCalculatorsLaminat.java
> +        calculateButton.click();
Исправил

2022-04-25 12:29 UTC, DenisKharitanuk commented on src/test/java/tests/SmokeTestCalculatorsLaminat.java
> +
Исправил

2022-05-30 10:46 UTC, wildpioneer commented
Проверено

2022-05-30 10:46 UTC, closed without merging