PageObject_Simple_HW
Den1sProkrastinator/TAF pull request #4
Opened 2022-05-11 18:04 UTC by Den1sProkrastinator

еще не догадался как передавать локаторы в метож getPageIdentifier  из BasePage не 
плодя классы

2022-05-30 10:45 UTC, wildpioneer requested changes

2022-05-30 10:45 UTC, wildpioneer commented on src/test/java/pages/MilestoneReviewPage.java
> +    public static class CheckStartMilestone extends BasePage {
В чем необходимость создания статичных классов тут?

2022-05-30 10:45 UTC, wildpioneer commented on src/test/java/pages/MilestonesPage.java
> +
Придерживайся единого форматирования по всем файлам

2022-05-30 10:45 UTC, wildpioneer commented on src/test/java/pages/MilestonesPage.java
> +    public static class CheckDeleteMilestone extends BasePage {
Опять какой-то класс для проверки - проверки чего?

2022-05-30 11:59 UTC, Den1sProkrastinator commented on src/test/java/pages/MilestonesPage.java
> +    public static class CheckDeleteMilestone extends BasePage {
Исправил

2022-05-30 11:59 UTC, Den1sProkrastinator commented on src/test/java/pages/MilestonesPage.java
> +
Исправил

2022-05-30 11:59 UTC, Den1sProkrastinator commented on src/test/java/pages/MilestoneReviewPage.java
> +    public static class CheckStartMilestone extends BasePage {
Исправил

2022-06-13 10:34 UTC, wildpioneer commented
Проверено

2022-06-13 10:34 UTC, closed without merging